server:
 port: 8888
spring:
 profiles:
  active: native
 cloud:
  config:
    server:
      native:
        searchLocations: file:///home/emkay/Projects/Microservices-in-Action-Implementation/configserver/src/main/resources/config/licenseservice