server:
  port: 8002
spring:
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
management:
  endpoints:
    web:
      exposure:
        include: env,health